# Generated by Django 4.0 on 2021-12-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/pictures/profilepic/default.jpg', null=True, upload_to='users/pictures/profilepic'),
        ),
    ]
