# Generated by Django 4.0 on 2022-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_banner_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='static/users/banner'),
        ),
    ]
